### ISSUE TITLE
Phase function for complex numbers

### ISSUE THREAD

**Issue by KurAnd10** [FlorianRappl/Mages#107]
Is it still possible to get a phase function for complex numbers returning radian. Sorry I forgot to check!

**Comment by KurAnd10** [comment]
Wouldn’t it be possible to handle that scenario according the already built in property “Phase” of the Complex datatype which is returning radians?  I think to use “rad” in this scenario is  confusing for the user because all other phase related parameters already need to be radians like when calculating “sin” or “asine”. Or do I miss something?

By the way “Arg” like defined in YAMP would be the better naming!

Thanks in advance,
Kurt

**Comment by FlorianRappl** [comment]
I am not sure what `Phase` of the complex datatype you are referring to. I guess you mean the .NET type; but we are not talking .NET here but MAGES (surely, we can expose it, but all I was mentioning is that the function is not yet exposed and how the function would look like).

Regarding the `rad` constant; this was just mentioned for completeness (that we could add more of these unit constants to have consistency here). Of course, `phase(c)` would be between `0` and `2pi`.

**Comment by KurAnd10** [comment]
Sorry for the confusion! Yes I mean “Phase” property of the “System.Numerics.Complex” datatype. To sum it up “PHASE” or better “ARG” returning values between 0 and 2pi would make me (us) very happy 😊!

Thanks again and all the best,
Kurt

**Comment by FlorianRappl** [comment]
Added `arg` for 2.0.1
