### ISSUE TITLE
String arrays

### ISSUE THREAD

**Issue by DiermenSoftware** [FlorianRappl/Mages#109]
Hi,

I really like this package, has tons of possibilities with a very good performance, however...
Currently arrays only work with numbers

Example:
eval("[5,6,7]")(1)   = 6    **< this already works**
eval("["A","B","C"]")(1)   = "B"     **< like this**

Thanks!

**Comment by FlorianRappl** [comment]
Yeah the thing is that the notation is not an array, but a matrix (which is numerical).

I think to use an array you'll need to fall back to `list`, e.g., `list("A", "B", "C")` may be usable.

Unfortunately, I think this is not really documented. I'll keep it open as a documentation topic.

**Comment by DiermenSoftware** [comment]
Ah thanks, didn't know the list yet. It works perfectly, thanks!
