### ISSUE TITLE
return 'sum' from a function like '(x) => sum=0; for(i=1;i<=x;i++) sum+=i; sum;'

### ISSUE THREAD

**Issue by hanlectin** [FlorianRappl/Mages#111]
Hi!

Is it siomehow possible to return a specific value from a function defined in Mages, i.e.
if i define a function
```
   var myfunc = engine.Interpret("(x) => x*2");
   var result = myfunc.Invoke(new Object[] { 7.0 });
```
then i get 14.0. fine!

but if i've got a 'method'-like function(*1) like:
```
   var myfunc = engine.Interpret("(x) => sum=0; for(i=1;i<=x;i++) sum+=i; sum;");
   var result = myfunc.Invoke(new Object[] { 100 });
```
I'd expect that the call returns 5050. but it's returning 100.

interpreting (i.e. engine.Interpret(...))
```
    var result = engine.Interpret("sum=0; for(i=1;i<=100;i+=1) {sum+=i;} sum;");
```
returns 5050.

is it somehow possible to return 'sum' from the above defined function *1)?

more info:
it returns 100 if there is no variable "sum" defined in Engine.Scope
otherwise it returns the value of "sum" (if it is defined in Engine.Scope)

thanks!

**Comment by FlorianRappl** [comment]
```
   var myfunc = engine.Interpret("(x) => sum=0; for(i=1;i<=x;i++) sum+=i; sum;");
   var result = myfunc.Invoke(new Object[] { 100.0 });
```

Can you try this (using a `double` instead of an `int`)?

**Comment by hanlectin** [comment]
unfortunately it's not working either...
I also tried:
```
var myfunc = engine.Interpret("(x) => sum=0.0; for(i=1.0;i<=x;i+=1.0) {sum+=i;} sum;");
var result = myfunc.Invoke(new Object[] { 100.0 });
```
--> result is whatever "sum" currently is in .Scope

then I tried (bracing the right term:
```
var myfunc = engine.Interpret("(x) => {sum=0.0; for(i=1.0;i<=x;i+=1.0) {sum+=i;} sum;}");
var result = myfunc.Invoke(new Object[] { 100.0 });
```
--> now it returns 101 (i.e. the last value of i)
BUT: in that case it updates "sum" in .Scope. 

so i tried: 
```
var myfunc = engine.Interpret("(x) => {sum=0.0; for(i=1.0;i<=x;i+=1.0) {sum+=i;} sum;} sum;");
```
--> which results in a ParseError

so, playing a litte more (using 'return'):
```
var myfunc = engine.Interpret("(x) => {sum=0.0; for(i=1.0;i<=x;i+=1.0) {sum+=i;} return sum;}");
var result = myfunc.Invoke(new Object[] { 100.0 });
```
--> !!! this finally yields the correct result !!!

also (*good)
```
var myfunc = engine.Interpret("(x) => {sum=0; for(i=1;i<=x;i+=1) {sum+=i;} return sum;}");
var result = myfunc.Invoke(new Object[] { 100.0 });
```
works fine!

whereas (no enclosing-braces)
```
var myfunc = engine.Interpret("(x) => sum=0.0; for(i=1.0;i<=x;i+=1.0) {sum+=i;} return sum;");
var result = myfunc.Invoke(new Object[] { 100.0 });
```
doesn't...

so the only problem for now:
(*good) creates two new variables "i" and "sum" in .Scope during execution
not a _huge_ issue, but still it would be nice if these "helper" variables are removed/hidden/... again after executing the function. any ideas?

thanks again!

**Comment by FlorianRappl** [comment]
I think if you use `var` and scope everything `{}` then it should work fine. (https://github.com/FlorianRappl/Mages/blob/devel/doc/syntax.md#statements)

The problem with your function was that it immediately return (`x => sum = 0.0`) whereas in the scoped one you run the loop in the function.

So my proposal would be:

```
var myfunc = engine.Interpret("(x) => {var sum=0; for(var i=1;i<=x;i+=1) {sum+=i;} return sum;}");
var result = myfunc.Invoke(new Object[] { 100.0 });
```

**Comment by hanlectin** [comment]
Thanks Florain, using "var" does the trick :)
and BTW: Kudos to MAGES! It's awesome!!!

**Comment by FlorianRappl** [comment]
Cool! Glad you like it!
