### ISSUE TITLE
Difference between SetConstant and Scope.Add

### ISSUE THREAD

**Issue by TomasaMuller** [FlorianRappl/Mages#115]
Hello,

I tried the following code
```

 Engine engine = new Engine();
 //engine.Scope.Add("time", 17);
 engine.SetConstant("time", 17);
 var result = engine.Interpret("(time > 12 ? (time - 12) + \" pm\" : time + \" am\")");
```
If I use `Scope` I get `(unknown) am`  as the result
If I use `SetConstant` I get the correct result as `5 pm`

What are the differences Between these 2 methods, when do we use one over the other?
I was wondering why `SetConstant` worked while `Scope` did not?

**Comment by FlorianRappl** [comment]
`SetConstant` introduces a new value into Mages - this implies conversation to the Mages data model.

`Scope` is the container for the values in Mages. If you introduce something directly here then you must supply valid data types. If you don't, then weird things can happen.

`Scope` is low-level data bin and `SetConstant` is an abstraction.

**Comment by TomasaMuller** [comment]
> `Scope` is the container for the values in Mages. If you introduce something directly here then you must supply valid data types. If you don't, then weird things can happen.

I did set it correctly with an int data type like this

`engine.Scope.Add("time", 17);`

yet it did not give the correct result.

**Comment by TomasaMuller** [comment]
Ok I get It, It looks like Mages need a double as a data type so If I do this 

`engine.Scope.Add("time", 17.0); // use a double literal value`

That gives a correct result.

**Comment by FlorianRappl** [comment]
> I did set it correctly with an int data type like this

No you did not. `Int32` is not a native type. You should make it `17.0`, as `Double` (called `Number`) is a native type in Mages.

Please look at the [documentation](https://github.com/FlorianRappl/Mages/blob/devel/doc/types.md).

**Comment by TomasaMuller** [comment]
> > I did set it correctly with an int data type like this
> 
> No you did not. `Int32` is not a native type. You should make it `17.0`, as `Double` (called `Number`) is a native type in Mages.
> 
> Please look at the [documentation](https://github.com/FlorianRappl/Mages/blob/devel/doc/types.md).

Yes I just replied a fraction of a second ago.
Apologies !

**Comment by FlorianRappl** [comment]
All good! Hope everything now works as it should!
