### ISSUE TITLE
Inline array initialization

### ISSUE THREAD

**Issue by TomasaMuller** [FlorianRappl/Mages#116]
Based on your comments on https://github.com/FlorianRappl/Mages/issues/17 and after reading the documentation

I was trying to initialize arrays and lists inline with Mages.
something like
`List<string> list = new List<string>{"a","b","c"};`

I see you have a function 
`list("a","b","c")` which will return a list

Also you can expose .net classes like so

`eng.SetStatic<System.Collections.Generic.List<System.Object>>().WithName("ArrayObj");
            eng.SetStatic<System.Collections.Generic.List<System.String>>().WithName("ArrayStr");
            eng.SetStatic<System.Collections.Generic.List<System.Int32>>().WithName("ArrayInt");
`
and then call  `ArrayObj.create()` to create a list.

My end goal is to create a typed list eg. `List<string>`, `List<int>` or `List<object>`

Is it possible to do something like 

`listStr = ArrayStr.create(["a", "b", "c"])`  \\ to create a preinitialized string array
`listInt = ArrayInt.create([1, 2, 3])` 

Is there some other syntax that I'm missing out on?

**Comment by FlorianRappl** [comment]
It's a good question. From the top of my head you are not missing anything there. Maybe we can support inline initialization (either directly, e.g., by convention or some extension method, or indirectly). I'll come back on this one.

**Comment by FlorianRappl** [comment]
The constructors in 2.0.2 automatically work here and allow you to do:

```
listInt = ArrayInt.create(1, 2, 3)
```

i.e., they behave as if they are using `params` in C#.
