### ISSUE TITLE
Possibility for switchable Scope

### ISSUE THREAD

**Issue by TomasaMuller** [FlorianRappl/Mages#119]
Is it possible to have multiple `Scope`. Here I'm referring to the `Scope` dictionary within `Mages`.
Use-case would be to set some variables in `Scope1` and some other variables in `Scope2` and so on ....
Then we should have the ability to change the Scope dynamically during runtime and the engine should use the variables in the currently selected `Scope.`

This also acts like a sandbox, where a part of the code only can access variables that it has access to and not touch other variables.

**Comment by FlorianRappl** [comment]
This will be part of 2.0.2 with the `SwitchableScope` (you could also write this class, but its now provided as a convenience out of the box).

**Comment by FlorianRappl** [comment]
Documentation on this one:

https://github.com/FlorianRappl/Mages/blob/devel/doc/advanced.md
