### ISSUE TITLE
Addition of randi() function

### ISSUE THREAD

**Issue by GhostVaibhav** [FlorianRappl/Mages#123]
Hi

I would like to know the feasibility of creating a new function `randInt()` that generates a random integer. It will take an integer `value` as the argument and generate a random integer between 0 < generated <= value.

**Comment by FlorianRappl** [comment]
I think we can do. My suggestion is to call it `randi(n)` where `n` is the inclusive upper boundary. We might also make `n` optional, with a default value of `100` (but having it required is also possible).

**Comment by GhostVaibhav** [comment]
Let's pass a required value rather than an optional one. Since I think that's most probably how it's implemented in all other places.
