### ISSUE TITLE
Incorrect number reading

### ISSUE THREAD

**Issue by josefblaha** [FlorianRappl/Mages#125]
There is a case where Mages incorrectly tokenizes a number. Some cases were fixed in #110, but not all of them.

## Steps to reproduce
Start REPL and evaluate the following numbers:
```
SWM> 0.8409014139716477191
0.8409014139716476
SWM> 0.84090141397164771912
0.10303165102326567
```
The first number correctly evaluated, losing precision as expected.
The second number (just adding `2` to the end) produces distorted result.

## Environment
Mages 3.0.0
Windows 11

## Cause
Since #110, the `NumberTokenizer.AddValue` method checks for some overflow cases, but not all of them. Specifically for the example number above it all goes well until the attempt to add the last digit `2`:
![image](https://github.com/user-attachments/assets/3d5885b1-8670-4088-bffe-2f4d99cf15a9)
The overflown `newValue = 10303165102326565448` is larger than `_value = 8409014139716477191`, therefore it's not ignored.

## Fix proposal
We should improve the overflow check. I will create a PR soon with a proposed fix.

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
