### ISSUE TITLE
Indexer not setting list value.

### ISSUE THREAD

**Issue by mercurial-moon** [FlorianRappl/Mages#127]
Hi,
My code is as under 
```
ee.SetStatic<System.Collections.Generic.List<System.Object>>().WithName("List");
ee.Interpret("a = List.create(); a.add(2); a.add(3); a.add(4);"); // (2, 3, 4)
ee.Interpret("a(1) = 10"); // still (2, 3, 4)

```
In the second step I expected the list to change to (2, 10, 4) but it didn't do that.
I have tried various alternatives like

```
a.at(1) = 10 // no change
a[1] = 10 // compile error
a(1) = a(2) // no change
```
Mages version is 2.0.2
Am I doing anything wrong here?

**Comment by FlorianRappl** [comment]
If you ask me the index proxy just is this function (see https://github.com/FlorianRappl/Mages/blob/devel/src/Mages.Core/Runtime/Proxies/IndexProxy.cs), so (without looking at it in detail) I'd assume that only the getter (as: `at`) is forwarded.

Maybe there should be an `updateAt` if a setter exists, too. That would be indeed a nice extension (for Mages v3).

**Comment by FlorianRappl** [comment]
> thanks for the reply.. is there a workaround in the interim for Mages 2.0.2

You can always add more functions yourself, which could then set the index.
