### ISSUE TITLE
Issues with handling hex numbers with a decimal point

### ISSUE THREAD

**Issue by PesBandi** [FlorianRappl/Mages#128]
For example the input `0x11.4` results in `6.800000000000001` instead of the expected `17.25`. I can imagine that implementing a fix could be quite challenging and I understand that working with non-integer hex numbers is really uncommon, however I think that maybe throwing a `ParseException` to let the user know that Mages doesn't support this would be beneficial.

**Comment by FlorianRappl** [comment]
Yeah I fully agree - I think that the current behavior is actually following an undefined path. The hex representation is not meant to mix with decimals (same goes for octal, binary, etc.). I think all these cases should not parse.

**Comment by FlorianRappl** [comment]
Just an explanation on the behavior:

- The hex parser (as well as others) actually don't parse the dot
- The ".4" is interpreted as "0.4" (you can also just enter ".1" standalone and see its "0.1")
- Two numbers that stand adjacent to each other are interpreted as a product (e.g., "3 4" will result in "12"); this is a specified feature that works especially well with "3pi" etc.

Still - it does not make sense for a hex number to have a direct dot continuation. So we will force a space in between (or anything; it just cannot be followed by a dot; so "0x11 .4" is still valid, but "0x11.4" is not.

**Comment by FlorianRappl** [comment]
Fix landed in the preview for 3.0.0.
