### ISSUE TITLE
Math -- returns an exception.

### ISSUE THREAD

**Issue by DiermenSoftware** [FlorianRappl/Mages#130]
In math it’s possible to write: 
```
1--1 // should return 2
--1 // should return 1
```
Where -- becomes +
I’m aware that this is also used to do this:
--parameter to lower the parameter by 1

Is it possible to fix this?

**Comment by FlorianRappl** [comment]
I actually don't think so. `--` is an operator (just like `-` is). So the correct way would be `1-(-1)` or `-(-1)` to distinguish between `--` (decrement operator) applied on `1` (a number) and `-` (negate operator) applied on `-1` (a number).

Of course, we could look ahead and determine if you provided a constant (number), but then it would be inconsistent (--1 and --a if `a` is 1 should yield the same - but with such a change it would not).

**Comment by DiermenSoftware** [comment]
I have tested in some other languages like JavaScript, it works the same way, also a error.
The key thing is that a space will also separate the logic. For example: 1 - -1 returns 2, also in Mages this works correctly!

**Comment by FlorianRappl** [comment]
Yes, anything that is not the operator (`--`) works - I just uses parenthesis for readability / groupability.

Great, then let's keep the behavior as-is - and I'd say let's release 3.0.0 tomorrow if there are no other rejections / bugs / areas of improvements that we see.
