### ISSUE TITLE
Provide map function

### ISSUE THREAD

**Issue by FlorianRappl** [FlorianRappl/Mages#33]
A map function would be useful to map (key, value) to (key, value' = f(value)) by a mapping function f. In conjunction with currying and the pipe-operator this would yield a powerful construct.

```C
new { a: "Hallo", b: "Name", c: [1,2,3] } | map(length) // new { a: 5, b: 4, c: 4 }
```

Another example:

```C
new { a: "Hallo", b: "Name", c: [1,2,3] } | map(is("String")) // new { a: true, b: true, c: false }
```

Of course we can also supply custom functions

```C
[1, 2, 3] | map(x => x^3 + x^2 - x) // new { "0": 1, "1": 11, "2": 31 }
```

Please note that a matrix has to be mapped to an Array-like object, as the mapping also works with non-number types.

**Comment by johncater** [comment]
[1,2,3] | map(x => x^3 + x^2 - x) would actually return new{"0": 1, "1": 10, "2": 33}
