### ISSUE TITLE
Global scope isn't global

### ISSUE THREAD

**Issue by matteofabbri** [FlorianRappl/Mages#52]
due to a  bug in GlobalScope / BaseScope functions defined in Global Scope are defined only in Global Scope.

```C
factorial(20)  //defined.
```

In contrast:

```C
while(1<2)
{
        factorial(20); //undefined
}
```

**Comment by FlorianRappl** [comment]
Thanks, I will look into this!

**Comment by FlorianRappl** [comment]
Are you sure that this is a bug? I think what you see is expected. `factorial` is still defined.

See:

```C
var f; if (true) { f = factorial; } f(5) == factorial(5) // true
```

Maybe the `undefined` was misleading, however, the `while` construct is a statement - statements do not yield values unless they are simple statements, which are plain expression holders.
