### ISSUE TITLE
Odd Implicit Conversion

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/Mages#70]
Say I have
`bool foo`
If I evaluate
`-foo+1`
foo is implicitly converted to a number and  evaluated as expected. However,
`1-foo`
will not evaluate at all, presumably because foo is not converted.

Given what I see in the Types documentation, I'm guessing this is the intended behavior. However it seems intuitive to me that bools and numbers should always implicitly cast to each other, is there some reason why they do not?

**Comment by FlorianRappl** [comment]
There is no reason for having this - and it should be added.

The technical reason for the difference is simple: Operators (such as add, subtract, ...) operate directly on the inputs - no assumptions being made. Thus, the add operator needs to trigger the cast - not the engine (it does not know what the operator can act on).

So for the unary operators some (useful) casts exist, but for binary operators some operations (e.g., number + bool or bool + number) does not exist. I will add them!
