### ISSUE TITLE
Variable change delegate?

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/Mages#71]
Would it be possible to add a Func<bool>() to go with the compiled Func<object>() delegate to check if any of the variables referenced by that expression have changed? I need to update most of my functions every frame, but the majority of those updates are unnecessary because the variables are all still the same. 

A bit of uninformed speculation: I suppose eventually something like this could be rolled into the branch-reducing optimizations, since often only one variable in the expression will change. For example, in the expression
`sin(t+sin(foo.position.x))`
the t variable will change every frame but foo.position.x might change only occasionally, so the sin(foo.position.x) branch can be reduced to a constant for most frames. This could really improve per-frame evaluation of expressions with a mix of variables that update at different frequencies.

PS: Should I be labeling these issues myself? Couldn't find a way to add labels. Still learning the GitHub etiquette, forgive me my trespasses.

**Comment by FlorianRappl** [comment]
Nope this won't be part of Mages. You can do that yourself - the scope can be provided (i.e., an instance of a class implementing the `IDictionary`. I think Mages already comes with such a class; the `ObservableDictionary`. You only need to use this instead of the (default) plain dictionary. That's it!

Generally I don't see why you need to recompile the expression. The reference is untouched! So you can still use the old `Func<T>`, which has the reference to the (now changed) value.

PS: I could make you contributor if you want that. Then you can just go ahead and add the labels yourself.

**Comment by SigmaEpsilonChi** [comment]
Abstract's scene data is contained in a hierarchy of widgets (`DataNode`), each of which has a hierarchy of values (`DataUnit`). In the game these work more or less like classes and fields. They both implement `IDictionary` so that `GetValue()` moves up the hierarchy much like `BaseScope` does. This works great—kudos on the `IDictionary` idea, it's perfect—but it also means I can't just check if any values in the scope have changed.

Forget the delegate idea, it's ugly anyway. I guess all I really need is a `Dictionary` of the keys/values reference by a given function string. Then I can check every frame if any entries have changed according to `DataUnit.GetValue()`. I have a workable way to do this in mind, but it's a little hacky (involves adding side effects to `DataUnit.GetValue()`). Before I implement that is there an existing way to get a list/dict with all the variable keys referenced by a function string?

Don't worry, `DataUnit` only recompiles the expression when its function is changed. Doing that every frame would be a catastrophe :)

And sure, if that makes anything easier for you. I was just unsure if I'm supposed to label issues myself according to GitHub law. Otherwise contributor status makes no difference to me.

**Comment by FlorianRappl** [comment]
There is a tree walker (the `SymbolTreeWalker`) to find all the referenced variables. I think this one could be the solution to your problem!

**Comment by SigmaEpsilonChi** [comment]
Confused by one aspect of the `SymbolTreeWalker`. I parse my source to a `BlockStatement`, create a `SymbolTreeWalker`, and tell it to visit the statement. It collects everything as I had expected, except for symbols on the right side of a member operator. So in `player.position.x` I get `player` but not `position` or `x`.

I assumed the AST represents `position.x` as a `MemberExpression` with a `VariableExpression` object/member, which the `SymbolTreeWalker` visits and collects on both sides, but it seems like that's not right. Can you clarify how `SymbolTreeWalker` works with members?

**Comment by FlorianRappl** [comment]
The `SymbolTreeWalker` will only collect the variables (`VariableExpression`), not the members of objects (these are `IdentifierExpression` instances in a `MemberExpression`).

So we could have three ways now:

- Also collect identifiers being accessed in these scenarios
- Provide the option to also collect the identifiers for members
- Have a distinct walker to get the used identifiers for all members

I prefer the third way as it would be the most flexible / extensible approach.

**Comment by SigmaEpsilonChi** [comment]
Ah, okay. Two questions then:

- Given `player.position.x`, Would the `MemberTreeWalker` (or whatever you name it) collect `player`, `position`, and `x`, or only the identifiers `position` and `x`? That is, would I need to use both `SymbolTreeWalker` and `MemberTreeWalker` to collect everything?

- Could there be a simple way to know the object each identifier is a member of? So, for example, the `x` in `position.x` and `size.x` would be collected separately with a simple way to know which `x` belongs to `position` and which belongs to `size`.

If the use case is checking/caching variables required by some compiled function on execution, then basically I need to collect every expression that results in a call to `TryGetValue()` in my scope `IDictionary` (plus the object that expression is a member of, if any).

**Comment by FlorianRappl** [comment]
In your example `player.position.x` you would get `position->player` and `x->position`, where `bar->foo` denotes "bar is a child of foo". The `bar` would be transported as a string, the `foo` as an expression (i.e., you could get the position, more info etc. on demand).

(the structure is an `IEnumerable<Tuple<String, IExpression>>`.)

So I think the way would/should be already quite simple.

**Comment by SigmaEpsilonChi** [comment]
If each entry is a `Tuple<String, IExpression>`, is there a way to disambiguate `position->x` given `foo.position.x` and `bar.position.x`? Would that be somehow accessible through the `IExpression`?

**Comment by FlorianRappl** [comment]
Yes, of course the `IExpression` is from the AST after all.
