### ISSUE TITLE
Referencing Vector Components

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/Mages#72]
At the moment, my vector values are just containers for three separate doubles. This makes it possible to reference things like `foo.position.x`. However, it's consequently not possible to do operations like `foo.position+bar.position`, or directly assign to `foo.position`.

Is there a way around this? Currently `foo.position` returns an IDictionary, if I make it convertible to a Double[,] could MAGES possibly treat it as a Double[,] for `foo.position` and an IDictionary for `foo.position.x`?

**Comment by FlorianRappl** [comment]
I don't see why you don't use `Double[,]` in the first place! Its a vector after all.

For your use case (providing convenient properties such as `x`, `y`, etc.) there are attached properties (see the features of MAGES). You just need to attach these properties to a matrix (potentially with the constraint that the matrix has 1x3 dimensions) and you are done.

See [this unit test](https://github.com/FlorianRappl/Mages/blob/master/src/Mages.Core.Tests/ExtensibilityTests.cs#L517) for a way how to do it.

**Comment by SigmaEpsilonChi** [comment]
This is all a bit of a holdover from the YAMP implementation, and more generally the quick/dirty demo stages of this game. However, there are a few other reasons why I haven't switched to `Double[,]` yet.

The `DataVector` class is a container for three `DataFloat`* objects, both derived from `DataUnit`, because for some things in Abstract it's convenient for the `DataUnit` functionality to be available for each component of the vector. In particular:

–Players can independently select and edit vector components, which are black when defined with a constant and blue when defined with a function. Right now the parent `DataVector` object can't be directly defined from the editor**, but I'd like for that to be possible in a way that is seamless with defining components individually***.
![florianvectormenuunit](https://cloud.githubusercontent.com/assets/15720465/19943575/5c9e04a0-a10e-11e6-87c1-05780d71b523.gif)

–When dragging objects to move/resize them, only components defined with constants are affected.
![florianvectordragstop](https://cloud.githubusercontent.com/assets/15720465/19943541/40371b44-a10e-11e6-9bf9-212bde33b4d0.gif)

–Optimizations like the one brought up in the 'Variable Change Delegate' issue happen in `DataUnit`, so having separate `DataFloat` objects lets those work for each component separately.

I've wanted to switch to `Double[,]` vectors for a while now, but I'm not sure how to do it without breaking these features. I'm hoping these aren't real obstacles and that I'm just thinking about it the wrong way. Any thoughts?

_*Unity uses floats almost exclusively, I only use doubles when talking to MAGES_

_**The mouse will hilight it, but clicking does nothing_

_***It's much more approachable for a lot of players, who may not even know what a vector is!_

**Comment by FlorianRappl** [comment]
Well, of course Unity uses floats - Unity is a 3D framework after all. But you should never confuse game logic with visuals. So separating the two is certainly helpful - and hence should not be a blocker for using doubles.

That being said: Potentially, we'll see operator overloading for types in MAGES. Right now it was planned with v2 with proper prototyping, but I assume that I can make it work in v1 already. But that won't be covered in this issue.

**Comment by SigmaEpsilonChi** [comment]
Just clarified the `DataFloat` bit in case you weren't familiar, since double precision is the standard everywhere else. Of course, casting to double is no issue :)

The logic and visuals are neatly separated, no problem there. All the UI/renderering/physics stuff only talks to Abstract's `Data` layer, which holds the internal scene representation and talks to MAGES. That layer also sandboxes users so they only indirectly interact with the parser; there is no assignment via MAGES, it just computes values which Abstract assigns internally. This has real benefits for optimization (easily culling needless evaluation), usability (lightening the syntax), and userproofing (skirting the halting problem—no direct loops or recursion allowed in Abstract).

I guess the bulk of the conflict lies in the UI, which wants to have both a simplified and a complete way of interacting with vectors which the `Data` layer must resolve to a single representation. But of course that has nothing to do with MAGES, and this is not the place to be thinking out loud. Besides, I've taken enough of your time today!
