### ISSUE TITLE
Vector Arithmetic

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/Mages#74]
Seems I can't perform arithmetic operations on vectors, which makes them hard to work with. Would appreciate support for +- on vector/vector operations, and */ on vector/scalar operations

**Comment by FlorianRappl** [comment]
What are you struggling with? MAGES follows the standard math rules.

See:

```c
SWM> [1,2,3]*[1;2;3]
[14]
SWM> [1,2,3]*[1,2,3]
Undefined
SWM> [1;2;3]*[1,2,3]
[1,2,3;2,4,6;3,6,9]
SWM> [1,2,3]+[1,2,3]
[2,4,6]
SWM> [1,2,3]-[1,2,3]
[0,0,0]
```

Note that division is only possible with matrices - and also only if the matrix divided by can be inverted.

**Comment by SigmaEpsilonChi** [comment]
Huh, odd. `[1, 2, 3]+[1, 2, 3]` returns `undefined` for me. There must be
something funny going on here, let me investigate a little deeper...

**Comment by SigmaEpsilonChi** [comment]
Nevermind, this was a bug in Abstract's pre-parsing stage. Sorry for the false alarm.

**Comment by SigmaEpsilonChi** [comment]
Nevermind, this was a bug in Abstract's pre-parsing stage. Sorry for the false alarm.

**Comment by FlorianRappl** [comment]
No problem, glad we figured that one out :)!
