### ISSUE TITLE
Clamp/Lerp

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/Mages#80]
Hey Florian, could you add `clamp(min, max, value)`, `clamp01(value)`, `lerp(min, max, value)`, and `inverselerp(min, max, value)` to the included functions? Couldn't find mention of them in the docs, apologies if they're there.

Hope you're having a good holiday season. Thanks for being such a dedicated, helpful, and patient project maintainer this year! MAGES is wonderful to work with and it transformed this project.

**Comment by FlorianRappl** [comment]
Hi Chris - thanks for the wishes (also merry Christmas and a nice holiday season for you, too!) and the function request. Indeed, these functions are not there.

I still have to validate if these functions would be a good fit to the core. In the meantime you can add these yourself. If they fit then `clamp01` would definitely not be included, as it is the outcome of `clamp(0, 1)`. So defining that in MAGES would be as simple as `clamp01 = clamp(0,1)`.

I will come back with a definite answer if (and which of them) make sense to be included in the core.

**Comment by FlorianRappl** [comment]
I'll include `clamp` and `lerp`.
