### ISSUE TITLE
Plugin Overloaded Methods

### ISSUE THREAD

**Issue by wootencl** [FlorianRappl/Mages#84]
Question: Is it possible to use overloaded methods within plugins? Looking at the `FileFunctions` of the `FileSystem` plugin it looked like it should be but after some brief testing that would seem to not be the case. For instance, if I have the following custom plugin functions:

```
public static string test_overload(string input) { return "Overload 1"; }

public static string test_overload(double input) { return "Overload 2"; }
```
and call the following: `engine.interpret("test_overload(4.56)")` it will _always_ print "Overload 1". Could be totally off base with this as well so any help would be greatly appreciated!

/cc @FlorianRappl

**Comment by FlorianRappl** [comment]
How are the two functions included? Are they included in the same fashion as the `FileFunctions` (via reflecting the `Type`)?

**Comment by wootencl** [comment]
Whoops.... completely missed that the `FileFunctions` are sub functions on the `File` property. The two functions in the example are being included such as the other plugins via a parent `...Plugin` class and then calling `AddPlugin(typeof(...Plugin))`. As a follow up question: is it possible to have vanilla method overloading on the base `...Plugin` class (instead of having to use reflection via a property)? Essentially avoiding the need to do `file.Create` and instead have the ability to do just `create`

**Comment by FlorianRappl** [comment]
I don't think it is implemented right now, but in general nothing speaks against it. As Mages only knows 1 object per identifier (remember every function is essentially just another object for Mages) it is impossible to achieve directly though. Instead you either need to pre-aggregate (combine the potential overloads into a single function that dispatches to the right target), or a 2-into-1 kind of thing where you jump from one to the next if nothing has been hit yet.

**Comment by wootencl** [comment]
Thanks for the prompt reply @FlorianRappl! Answers my question sufficiently enough to close this issue. Ended up going with the pre-aggregating approach and doing some quick type checking.
