### ISSUE TITLE
Potential String Comparison Bug

### ISSUE THREAD

**Issue by wootencl** [FlorianRappl/Mages#85]
Hi @FlorianRappl,

Have a potential string comparison bug related to escaped characters. The following example code will return false (though it should return true).
```
var engine = new Engine();
var x = "1/2\\\"";
engine.Scope["MVIP_PRODUCT"] = x;
var y = x == "1/2\\\""; 
Console.WriteLine(y); // TRUE as expected
var result = engine.Interpret("MVIP_PRODUCT == \"1/2\\\"\"");
Console.WriteLine(result); // FALSE
```

More than likely an extreme edge case but figured it might be worth mentioning.

**Comment by FlorianRappl** [comment]
I don't think this is a bug. The `x` you entered is `1/2\"`. The literal that MAGES sees is `1/2\"`. Now that looks equal at first - right - but remember that the `x` is already stored that way, while the literal is still being evaluated. Thus, the literal will now become `1/2"` (escaped quote).

I guess the literal written in C# for the literal in MAGES should `1/2\\\"`, i.e.,

```c
var result = engine.Interpret("MVIP_PRODUCT == \"1/2\\\\\\"\"");
```

To be a little bit less confusing I would propose using C# string literals:

```c
var result = engine.Interpret(@"MVIP_PRODUCT == ""1/2\\\""");
```

I hope I did not make any mistake, but I guess you get the idea. Two layers of string literals are confusing and one needs to watch out very carefully. BTW: In MAGES you can also use the at symbol to avoid escape sequences.

**Comment by wootencl** [comment]
Hi @FlorianRappl,

Sorry for the delayed response. Once again it would seem you are correct. Believe it was probably a misunderstanding on my part on how/when MAGES was evaluating the strings. With that, I was able to develop a workable solution so I'll be closing this issue. 

Definitely a confusing situation with so many string literals. Thanks for the help.
