### ISSUE TITLE
Parser cannot parse integers greater than 2147483648

### ISSUE THREAD

**Issue by huwcbjones** [FlorianRappl/Mages#88]
See https://github.com/Wox-launcher/Wox/issues/1950

When entering a number greater than 2147483648, the result is always -2147483648

**Comment by FlorianRappl** [comment]
Mages does not support arbitrary digits. It is true that input beyond that should be allowed, but it would lead to highly unexpected results (at this point 64-bit floating point numbers will be used, which is the final output anyway, but accumulating input in an accurate integer fashion for an inaccurate floating point seems to be odd at least; for comparison see JS at the bottom of this answer).

So the question is: What is the expectation? Let's say we increase the bits, a new bug would be opened with, e.g., 9223372036854775807 as value (same behavior - the overflow resulting in a negative number). Should Mages instead raise an error (most statically compiled languages do that)?

Now for the inaccurate part: In some sense Mages is similar to JS. So if we switch on this behavior we would get things such as:

```js
var a = 9223372036854775807
a // 9223372036854776000
```

Granted it would give us a little bit more runway, but in a calculator the behavior will still seem odd.

**Comment by huwcbjones** [comment]
I honestly don't know.
As you rightly said, we'll always encounter some arbitrary cap and unexpected behaviour.

I still think raising the maximum would be beneficial. However, I think documenting the limitation would also be beneficial.

There is of course the option to parse floats and integers using different logic, but yet again that would introduce a whole new load of issues!

But yeah, I don't think there is a "best" way at all...

**Comment by FlorianRappl** [comment]
Agreed - will be documented and Mages will actually have the same behavior as JS (see example above).
