### ISSUE TITLE
Clamp(int min, int max, string value) ignores min  if value.Length > max

### ISSUE THREAD

**Issue by johncater** [FlorianRappl/Mages#89]
Currently Clamp ignores "min" if value.Length is greater than "max" and returns value.Substring(0, max).  In Helpers.cs (line 71-84):

```
public static String Clamp(this String value, Int32 min, Int32 max)
        {
            if (value.Length < min)
            {
                return value.PadRight(min, ' ');
            }
            else if (value.Length > max)
            {
                return value.Substring(0, max);
            }
            return value;
        }
```

Use case:
I want to get the hours, minutes, seconds from this string "2018-06-29T12:27:00.00000" but clamp(12, 19, "2018-06-29T12:27:00.00000") returns "2018-06-29T12:27:00".

**Comment by FlorianRappl** [comment]
Yep sounds reasonable. So how would you change the implementation?

General question: Would a new function make more sense? Right now clamp for a string returns a string that is at least of length `min` (padding with spaces if necessary) and at most of length `max` (cutting if necessary). I think what you are after is more a substring implementation, right?

**Comment by johncater** [comment]
Thanks for responding so quickly.  For this particular use case I'm going to build a custom expression to mirror String.Replace(), but for a more generally applicable solution I would expect clamp to behave similarly to it's mathematical implementation.  Something like this:

`public static String Clamp(this String value, Int32 min, Int32 max)
        {
            if (value.Length < min)
            {
                return value.PadRight(min, ' ');
            }
            else if (value.Length > max)
            {
                return value.Substring(min, 1 + max - min);
            }
            else if (value.Length <= max)
            {
                return value.Substring(min, 1 + value.Length - min);
            }
            return value;
        }`

And thank you for building such a bad ass tool and sharing it freely.

**Comment by johncater** [comment]
Ah, good point.  A new function makes sense and `Clip` works fine for me.
