### ISSUE TITLE
Add hyperbolic functions

### ISSUE THREAD

**Issue by pavelzw** [FlorianRappl/Mages#92]
It would be nice to be able to type `sinh(0)`, `cosh(0)`, `tanh(0)`, `arsinh(0)`, `arcosh(0)`, `artanh(0)` into the engine.

**Comment by FlorianRappl** [comment]
Hm these should be there (see, e.g., https://github.com/FlorianRappl/Mages/blob/master/src/Mages.Core/Runtime/Functions/StandardFunctions.cs#L415).

Did you activate / integrate the standard functions?

**Comment by pavelzw** [comment]
Ah okay! 
I only looked at the [functions markdown document](https://github.com/FlorianRappl/Mages/blob/master/doc/functions.md). 
Maybe you should add them there.
