### ISSUE TITLE
Use e in input

### ISSUE THREAD

**Issue by pavelzw** [FlorianRappl/Mages#93]
Hi,
I'm trying to use e with mages. 

```
Engine engine = new Engine();
var result = engine.Interpret("e");
```

In this example, `result` is `null`. Would it be possible to add e the same way as pi?

Also, stuff like `"log(e)"` or `"sin(e)"` get evaluated `NaN`.

**Comment by FlorianRappl** [comment]
Well, `pi` is a keyword in MAGES, however, `e` is not.

You can provide `e` in your engine.

```
var engine = new Engine(new Configuration {
  Scope = new Dictionary<string, object> {
    { "e", Math.E }
  }
});

**Comment by pavelzw** [comment]
Thanks!
